


on:
  pull_request: 
    branches:
      - main
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-runner-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        
      - name: Print welcome msg
        run: |
          echo "welcome message"

      - name: Check current directory
        run: |
          pwd

      - name: list repo content
        run: |
          ls -l github-actions-test
